// Generated by PixelGen v2 - Multi-Page with Shared Components
// Page: blog

// ========== BLOG CONTENT 1 ==========
const Section2 = () => {
  const [hoveredCard, setHoveredCard] = React.useState(null);

  const getAsset = (i) => {
    const gifs = [23, 29, 31, 32, 33];
    const ext = gifs.includes(i) ? 'gif' : 'webp';
    return `./assets/img-${i}.${ext}`;
  };

  const ChevronRight = ({ className }) => (
    <svg className={className} width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M9 18l6-6-6-6" />
    </svg>
  );

  const ChevronLeft = ({ className }) => (
    <svg className={className} width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M15 18l-6-6 6-6" />
    </svg>
  );

  const SettingsIcon = ({ className }) => (
    <svg className={className} width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="3"></circle>
      <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path>
    </svg>
  );

  const heroSubLinks = [
    { category: "Developer Tools & Techniques", title: "NVIDIA CUDA 13.1 Powers Next-Gen GPU Programming with NVIDIA CUDA Tile and Performance Gains" },
    { category: "Data Science", title: "Simplify GPU Programming with NVIDIA CUDA Tile in Python" },
    { category: "Developer Tools & Techniques", title: "Focus on Your Algorithm—NVIDIA CUDA Tile Handles the Hardware" },
    { category: "Agentic AI / Generative AI", title: "NVIDIA-Accelerated Mistral 3 Open Models Deliver Efficiency, Accuracy at Any Scale" },
    { category: "Simulation / Modeling / Design", title: "How to Scale Data Generation for Physical AI with the NVIDIA Cosmos Cookbook" },
  ];

  const recommended = [
    { img: 3, date: "Dec 5, 2025", title: "NVIDIA Kaggle Grandmasters Win Artificial General...", desc: "NVIDIA researchers on Friday won a key Kaggle competition many in the field treat as a real-time pulse...", read: "3 MIN READ" },
    { img: 4, date: "Dec 2, 2025", title: "AWS Integrates AI Infrastructure with NVIDIA NVLink Fusion for...", desc: "As demand for AI continues to grow, hyperscalers are looking for ways to accelerate deployment of...", read: "5 MIN READ" },
    { img: 5, date: "May 2, 2025", title: "An Even Easier Introduction to CUDA (Updated)", desc: "A quick and easy introduction to CUDA programming for GPUs. This post dives into CUDA C++ with a...", read: "16 MIN READ" },
    { img: 6, date: "Oct 20, 2025", title: "Scaling Large MoE Models with Wide Expert Parallelism on NVL72 Ra...", desc: "Modern AI workloads have moved well beyond single-GPU inference serving. Model parallelism, which...", read: "10 MIN READ" },
  ];

  const recent = [
    { img: 7, date: "Dec 8, 2025", title: "Automate Kubernetes AI Cluster Health with NVSentinel", desc: "Kubernetes underpins a large portion of all AI workloads in production. Yet, maintaining GPU...", read: "7 MIN READ" },
    { img: 8, date: "Dec 8, 2025", title: "Optimizing Inference for Long Context and Large Batch Sizes with NVFP4...", desc: "Quantization is one of the strongest levers for large-scale inference. By reducing the...", read: "10 MIN READ" },
    { img: 9, date: "Dec 5, 2025", title: "NVIDIA Kaggle Grandmasters Win Artificial General...", desc: "NVIDIA researchers on Friday won a key Kaggle competition many in the field treat as a real-time puls...", read: "3 MIN READ" },
    { img: 10, date: "Dec 5, 2025", title: "NVIDIA Grace CPU Delivers High Bandwidth and Efficiency for Modern Dat...", desc: "Since its debut in 2023, the NVIDIA Grace CPU has experienced rapid adoption acros...", read: "8 MIN READ" },
  ];

  const categories = [
    {
      title: "Inference Performance",
      items: [
        { img: 11, date: "Nov 10, 2025", title: "Streamline Complex AI Inference on Kubernetes with NVIDIA Grove", desc: "Over the past few years, AI inference has evolved from single-model, single-pod deployments...", read: "10 MIN READ" },
        { img: 12, date: "Oct 20, 2025", title: "Scaling Large MoE Models with Wide Expert Parallelism on NVL72 Rac...", desc: "Modern AI workloads have moved well beyond single-GPU inference serving. Model parallelism, which...", read: "10 MIN READ" },
        { img: 13, date: "Oct 13, 2025", title: "NVIDIA Blackwell Leads on SemiAnalysis InferenceMAX v1...", desc: "SemiAnalysis recently launched InferenceMAX v1, a new open source initiative that provides a...", read: "11 MIN READ" },
        { img: 14, date: "Sep 29, 2025", title: "Smart Multi-Node Scheduling for Fast and Efficient LLM Inference...", desc: "The exponential growth in large language model complexity has created challenges, such as...", read: "9 MIN READ" },
      ]
    },
    {
      title: "Build AI Agents",
      items: [
        { img: 15, date: "Nov 07, 2025", title: "Building an Interactive AI Agent for Lightning-Fast Machine Learning Tasks", desc: "Data scientists spend a lot of time cleaning and preparing large, unstructured datasets before...", read: "8 MIN READ" },
        { img: 16, date: "Oct 22, 2025", title: "Create Your Own Bash Computer Use Agent with NVIDIA Nemotron in One...", desc: "What if you could talk to your computer and have it perform tasks through the Bash terminal...", read: "14 MIN READ" },
        { img: 17, date: "Oct 20, 2025", title: "Build an AI Agent to Analyze IT Tickets with NVIDIA Nemotron", desc: "Modern organizations generate a massive volume of operational data through ticketing systems,...", read: "11 MIN READ" },
        { img: 18, date: "Oct 10, 2025", title: "Build a Log Analysis Multi-Agent Self-Corrective RAG System with NVIDIA...", desc: "Logs are the lifeblood of modern systems. But as applications scale, logs often grow into endless wall...", read: "5 MIN READ" },
      ]
    },
    {
      title: "Agentic AI / Generative AI",
      items: [
        { img: 19, date: "Dec 03, 2025", title: "How to Enhance 3D Gaussian Reconstruction Quality for Simulation", desc: "Building truly photorealistic 3D environments for simulation is challenging. Even with advanced...", read: "7 MIN READ" },
        { img: 20, date: "Dec 02, 2025", title: "NVIDIA-Accelerated Mistral 3 Open Models Deliver Efficiency,...", desc: "The new Mistral 3 open model family delivers industry-leading accuracy, efficiency, and...", read: "6 MIN READ" },
        { img: 21, date: "Dec 01, 2025", title: "Train Small Orchestration Agents to Solve Big Problems", desc: "Using the right tool and model for a task is a challenging and ever-present engineering problem in...", read: "7 MIN READ" },
        { img: 22, date: "Dec 01, 2025", title: "Build Efficient Financial Data Workflows with AI Model Distillation", desc: "Large language models (LLMs) in quantitative finance are increasingly being used for alpha...", read: "11 MIN READ" },
      ]
    },
    {
      title: "Robotics",
      items: [
        { img: 23, date: "Dec 01, 2025", title: "How to Scale Data Generation for Physical AI with the NVIDIA Cosmos...", desc: "Building powerful physical AI models requires diverse, controllable, and physically-...", read: "9 MIN READ" },
        { img: 24, date: "Nov 25, 2025", title: "Making Robot Perception More Efficient on NVIDIA Jetson Thor", desc: "Building autonomous robots requires robust, low-latency visual perception for depth, obstacle...", read: "15 MIN READ" },
        { img: 25, date: "Nov 04, 2025", title: "R²D²: Perception-Guided Task & Motion Planning for Long-Horizon...", desc: "Traditional task and motion planning (TAMP) systems for robot manipulation use cases operate o...", read: "6 MIN READ" },
        { img: 26, date: "Oct 24, 2025", title: "Build Synthetic Data Pipelines to Train Smarter Robots with NVIDIA Isaac...", desc: "As robots take on increasingly dynamic mobility tasks, developers need physics-accurate simulation...", read: "9 MIN READ" },
      ]
    },
    {
      title: "Data Science",
      items: [
        { img: 27, date: "Nov 24, 2025", title: "Model Quantization: Concepts, Methods, and Why It Matters", desc: "AI models are becoming increasingly complex, often exceeding the capabilities of...", read: "12 MIN READ" },
        { img: 28, date: "Nov 10, 2025", title: "Training XGBoost Models with GPU-Accelerated Polars DataFrames", desc: "One of the many strengths of the PyData ecosystem is interoperability, which enables...", read: "7 MIN READ" },
        { img: 29, date: "Nov 10, 2025", title: "How to Achieve 4x Faster Inference for Math Problem Solving", desc: "Large language models can solve challenging math problems. However, making them work...", read: "7 MIN READ" },
        { img: 30, date: "Nov 06, 2025", title: "Enhancing GPU-Accelerated Vector Search in Faiss with NVIDIA cuVS", desc: "As companies collect more unstructured data and increasingly use large language models (LLMs...", read: "11 MIN READ" },
      ]
    },
    {
      title: "Simulation / Modeling / Design",
      items: [
        { img: 31, date: "Dec 02, 2025", title: "Accelerating Real-Time Financial Decisions with Quantitative Portfolio...", desc: "Financial portfolio optimization is a difficult yet essential task that has been consistently challenged by ...", read: "15 MIN READ" },
        { img: 32, date: "Nov 19, 2025", title: "Building Better Qubits with GPU-Accelerated Computing", desc: "Quantum computing promises to revolutionize science and industry, from drug discovery to materials...", read: "5 MIN READ" },
        { img: 33, date: "Nov 18, 2025", title: "Faster Chemistry and Materials Discovery with AI-Powered Simulations...", desc: "Almost all manufactured products are enabled by chemistry and materials science. However, new...", read: "6 MIN READ" },
        { img: 34, date: "Nov 12, 2025", title: "Just Released: Warp 1.10 Expands JAX Interoperability and...", desc: "Build high-performance GPU simulations using Warp, with enhancements across JAX, Tile...", read: "1 MIN READ" },
      ]
    },
    {
      title: "Computer Vision / Video Analytics",
      items: [
        { img: 3, date: "Nov 10, 2025", title: "Upcoming Livestream: Build Visual AI Agents with NVIDIA Cosmos Reason...", desc: "On November 18, learn how to fine-tune the NVIDIA Cosmos Reason VLM with your own data t...", read: "1 MIN READ" },
        { img: 4, date: "Nov 03, 2025", title: "Make Sense of Video Analytics by Integrating NVIDIA AI Blueprints", desc: "Organizations are increasingly seeking ways to extract insights from video, audio, and other...", read: "11 MIN READ" },
        { img: 5, date: "Oct 28, 2025", title: "Develop Specialized AI Agents with New NVIDIA Nemotron Vision, RAG, an...", desc: "Agentic AI is an ecosystem where specialized language and vision models work together. They hand...", read: "9 MIN READ" },
        { img: 6, date: "Sep 25, 2025", title: "How to Integrate Computer Vision Pipelines with Generative AI and...", desc: "Generative AI is opening new possibilities for analyzing existing video streams. Video analytics ar...", read: "10 MIN READ" },
      ]
    },
    {
      title: "Content Creation / Rendering",
      items: [
        { img: 7, date: "Nov 13, 2025", title: "How to Get Started with Neural Shading for Your Game or Application", desc: "For the past 25 years, real-time rendering has been driven by continuous hardware...", read: "21 MIN READ" },
        { img: 8, date: "Oct 21, 2025", title: "NVIDIA ACE Adds Open Source Qwen3 SLM for On-Device Deployment in PC...", desc: "To help create real-time, dynamic NPC game characters, NVIDIA ACE now supports the open source...", read: "4 MIN READ" },
        { img: 9, date: "Sep 30, 2025", title: "How id Software Used Neural Rendering and Path Tracing in DOOM: The Dar...", desc: "DOOM: The Dark Ages pushes real-time graphics to new limits by integrating RTX neural rendering...", read: "6 MIN READ" },
        { img: 10, date: "Sep 24, 2025", title: "NVIDIA Open Sources Audio2Face Animation Model", desc: "By leveraging large language and speech models, generative AI is creating intelligent 3D avatars th...", read: "7 MIN READ" },
      ]
    },
    {
      title: "Edge Computing",
      items: [
        { img: 11, date: "Oct 28, 2025", title: "Powering AI-Native 6G Research with the NVIDIA Sionna Research Kit", desc: "Wireless communication research is rich with brilliant ideas and computational power. Yet, there’s...", read: "6 MIN READ" },
        { img: 12, date: "Oct 24, 2025", title: "How NVIDIA DGX Spark's Performance Enables Intensive AI Tasks", desc: "Today’s demanding AI developer workloads often need more memory than desktop systems...", read: "5 MIN READ" },
        { img: 13, date: "Oct 15, 2025", title: "Accelerated and Distributed UPF for the Era of Agentic AI and 6G", desc: "The telecommunications industry is innovating rapidly toward 6G for both AI-native Radio Access...", read: "10 MIN READ" },
        { img: 14, date: "Sep 02, 2025", title: "What’s New in CUDA Toolkit 13.0 for Jetson Thor: Unified Arm...", desc: "The world of embedded and edge computing is about to get faster, more efficient, and more versatile...", read: "12 MIN READ" },
      ]
    },
    {
      title: "Data Center / Cloud",
      items: [
        { img: 15, date: "Dec 02, 2025", title: "AWS Integrates AI Infrastructure with NVIDIA NVLink Fusion for...", desc: "As demand for AI continues to grow, hyperscalers are looking for ways to accelerate deployment of...", read: "5 MIN READ" },
        { img: 16, date: "Nov 25, 2025", title: "Making GPU Clusters More Efficient with NVIDIA Data Center Monitoring Tools", desc: "High-performance computing (HPC) customers continue to scale rapidly, with generative AI, large...", read: "9 MIN READ" },
        { img: 17, date: "Nov 17, 2025", title: "NVIDIA NVQLink Architecture Integrates Accelerated Computing...", desc: "Quantum computing is entering an era where progress will be driven by the integration of accelerated...", read: "8 MIN READ" },
        { img: 18, date: "Nov 12, 2025", title: "NVIDIA Blackwell Architecture Sweeps MLPerf Training v5.1...", desc: "The NVIDIA Blackwell architecture powered the fastest time to train across every MLPerf Training v5.1...", read: "10 MIN READ" },
      ]
    }
  ];

  const Card = ({ item, dark }) => (
    <div className={`flex flex-col h-full group cursor-pointer ${dark ? 'text-white' : 'text-[#1a1a1a]'}`}>
      <div className="relative overflow-hidden mb-4 aspect-[16/9]">
        <img 
          src={getAsset(item.img)} 
          alt={item.title} 
          className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
        />
      </div>
      <div className="flex flex-col flex-grow">
        <span className={`text-[10px] font-bold uppercase mb-2 ${dark ? 'text-gray-400' : 'text-gray-500'}`}>
          {item.date}
        </span>
        <h3 className={`text-[16px] font-bold leading-tight mb-2 group-hover:text-[#76b900] transition-colors line-clamp-3`}>
          {item.title}
        </h3>
        <p className={`text-[13px] leading-relaxed mb-4 line-clamp-3 ${dark ? 'text-gray-300' : 'text-gray-700'}`}>
          {item.desc}
        </p>
        <div className="mt-auto">
          <span className={`text-[10px] font-bold uppercase ${dark ? 'text-gray-400' : 'text-gray-500'}`}>
            {item.read}
          </span>
        </div>
      </div>
    </div>
  );

  const CarouselRow = ({ title, items, dark = false }) => (
    <div className={`w-full py-10 border-b ${dark ? 'border-gray-800' : 'border-gray-200'}`}>
      <div className="max-w-[1440px] mx-auto px-4 md:px-8">
        <div className="flex justify-between items-center mb-6">
          <h2 className={`text-2xl font-bold ${dark ? 'text-white' : 'text-[#1a1a1a]'}`}>{title}</h2>
          {title === "Recommended For You" ? (
            <button className="flex items-center gap-2 text-sm font-bold text-gray-400 hover:text-white transition-colors">
              <SettingsIcon className="w-4 h-4" />
              Select Your Interests
            </button>
          ) : (
            <a href="#" className="flex items-center gap-1 text-xs font-bold hover:underline">
              See all <ChevronRight className="w-3 h-3" />
            </a>
          )}
        </div>
        
        <div className="relative group/carousel">
          {/* Navigation Arrows (Visual only as per static requirement, but positioned correctly) */}
          <div className="absolute -left-4

// ========== SECTION 3 ==========
const Section3 = () => {
  const posts = [
    {
      date: "Oct 03, 2025",
      title: "Enable Gang Scheduling and Workload Prioritization in Ray with NVIDIA KAI...",
      excerpt: "NVIDIA KAI Scheduler is now natively integrated with KubeRay, bringing the same scheduling...",
      readTime: "10 MIN READ"
    },
    {
      date: "Sep 10, 2025",
      title: "Maximizing Low-Latency Networking Performance for Financial Services wit...",
      excerpt: "Ultra-low latency and reliable packet delivery are critical requirements for modern...",
      readTime: "10 MIN READ"
    },
    {
      date: "Sep 09, 2025",
      title: "How to Connect Distributed Data Centers Into Large AI Factories...",
      excerpt: "AI scaling is incredibly complex, and new techniques in training and inference are continually...",
      readTime: "6 MIN READ"
    },
    {
      date: "Sep 03, 2025",
      title: "North-South Networks: The Key to Faster Enterprise AI Workloads",
      excerpt: "In AI infrastructure, data fuels the compute engine. With evolving agentic AI systems, where multipl...",
      readTime: "9 MIN READ"
    }
  ];

  return (
    <footer data-section="section-3" className="w-full bg-[#eeeeee] py-10 relative font-sans">
      <div className="max-w-[1400px] mx-auto px-12 relative">
        
        {/* Left Navigation Button */}
        <button 
          className="absolute left-0 top-1/2 -translate-y-1/2 z-10 w-10 h-12 flex items-center justify-center bg-[#b4d868] hover:bg-[#a3c65a] transition-colors -ml-4 lg:-ml-12 cursor-pointer"
          aria-label="Previous"
        >
          <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M5 1L1 7L5 13" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </button>

        {/* Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {posts.map((post, idx) => (
            <div key={idx} className="bg-white p-6 flex flex-col h-full min-h-[320px] shadow-sm hover:shadow-md transition-shadow border border-transparent hover:border-gray-200">
              <div className="text-xs text-gray-600 mb-3 font-medium tracking-wide">
                {post.date}
              </div>
              <h3 className="text-[18px] leading-snug font-bold text-black mb-3 line-clamp-3">
                {post.title}
              </h3>
              <p className="text-[14px] leading-relaxed text-gray-600 mb-4 line-clamp-3">
                {post.excerpt}
              </p>
              <div className="mt-auto text-[10px] font-bold text-black uppercase tracking-wider">
                {post.readTime}
              </div>
            </div>
          ))}
        </div>

        {/* Right Navigation Button */}
        <button 
          className="absolute right-0 top-1/2 -translate-y-1/2 z-10 w-10 h-12 flex items-center justify-center bg-[#76b900] hover:bg-[#6aa600] transition-colors -mr-4 lg:-mr-12 cursor-pointer"
          aria-label="Next"
        >
          <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M3 1L7 7L3 13" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </button>

      </div>

      {/* Bottom decorative bar */}
      <div className="absolute bottom-0 left-0 w-full h-4 bg-white border-t border-gray-200 flex justify-between items-end">
         <div className="w-8 h-full bg-[#76b900]"></div>
         <div className="w-8 h-full bg-[#76b900]"></div>
      </div>
    </footer>
  );
};

// ========== SHARED FOOTER ==========
const SharedFooter = () => {
  return (
    <footer data-section="section-5" className="w-full font-sans">
      {/* Top Section: Black Background */}
      <div className="bg-black w-full py-12">
        <div className="max-w-[1440px] mx-auto px-6 lg:px-12 flex flex-col lg:flex-row justify-between items-center gap-8">
          
          {/* Left: Newsletter Signup */}
          <div className="flex flex-col sm:flex-row items-center gap-6 w-full lg:w-auto justify-center lg:justify-start">
            {/* Envelope Icon */}
            <div className="text-white flex-shrink-0">
              <svg width="48" height="36" viewBox="0 0 48 36" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-12 h-9">
                <rect x="1" y="1" width="46" height="34" stroke="white" strokeWidth="1.5"/>
                <path d="M1 1L24 20L47 1" stroke="white" strokeWidth="1.5"/>
              </svg>
            </div>
            
            <span className="text-white text-xl font-bold tracking-tight text-center sm:text-left">
              Sign up for NVIDIA News
            </span>
            
            <button className="bg-[#76b900] hover:bg-[#6aa600] text-black font-bold text-base py-2 px-6 transition-colors duration-200 whitespace-nowrap">
              Subscribe
            </button>
          </div>

          {/* Right: Social & Blog */}
          <div className="flex flex-col items-center lg:items-end gap-1 w-full lg:w-auto">
            {/* Social Row */}
            <div className="flex flex-col sm:flex-row items-center gap-4 mb-1">
              <span className="text-[#a1a1a1] text-base font-medium">Follow NVIDIA Developer</span>
              <div className="flex items-center gap-3 text-[#a1a1a1]">
                {/* Facebook */}
                <a href="#" data-external className="hover:text-white transition-colors">
                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path></svg>
                </a>
                {/* Instagram */}
                <a href="#" data-external className="hover:text-white transition-colors">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37z"/><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"/></svg>
                </a>
                {/* LinkedIn */}
                <a href="#" data-external className="hover:text-white transition-colors">
                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
                </a>
                {/* X (Twitter) */}
                <a href="#" data-external className="hover:text-white transition-colors">
                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
                </a>
                {/* YouTube */}
                <a href="#" data-external className="hover:text-white transition-colors">
                  <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"/></svg>
                </a>
              </div>
            </div>
            {/* Blog Link */}
            <div className="text-sm text-[#a1a1a1] text-center lg:text-right">
              Find more news and tutorials on <a href="/blog" className="text-white border-b border-[#76b900] pb-[1px] hover:text-[#76b900] transition-colors">NVIDIA Technical Blog</a>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Section: Dark Gray Background */}
      <div className="bg-[#222222] w-full py-12">
        <div className="max-w-[1440px] mx-auto px-6 lg:px-12">
          
          {/* Logo */}
          <div className="mb-8">
             <div className="flex items-center select-none">
                {/* Green Swirl Icon */}
                <svg className="h-8 w-10 mr-2" viewBox="0 0 64 64" fill="#76b900">
                  <path d="M4 32c0-11 6-21 15-26 1.5-.8 3.5-.5 4.5 1s.5 3.5-1 4.5C16 15 12 23 12 32s4 17 10.5 20.5c1.5 1 2 3 1 4.5s-3 2-4.5 1C10 53 4 43 4 32z"/>
                  <path d="M32 4c-1.7

// ========== MAIN APP ==========
const App = () => {
  return (
    <div className="min-h-screen">
      <Section1 />
      <Section2 />
      <Section3 />
      <Section4 />
      <Section5 />
    </div>
  );
};

// ========== MAIN APP ==========
const App = () => {
  return (
    <div className="min-h-screen">
      <Section2 />
      <SharedFooter />
    </div>
  );
};