// Generated by PixelGen v2 - Multi-Page with Shared Components
// Page: pages-our-policies

// ========== PAGES-OUR-POLICIES CONTENT 1 ==========
const Section2 = () => {
  return (
    <footer data-section="about-us" className="w-full bg-white pt-14 pb-8">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <div className="flex flex-col md:flex-row justify-between items-start gap-10">
          
          {/* Logo Section */}
          <div className="flex-shrink-0">
            <a href="/">
              <img 
                src="./assets/img-1.png" 
                alt="Kilrr Logo" 
                className="h-[50px] w-auto object-contain" 
              />
            </a>
          </div>

          {/* About Us Section */}
          <div className="flex-1 max-w-[400px] md:mx-auto">
            <h3 className="text-xs font-medium tracking-[0.15em] text-gray-800 uppercase mb-4">
              About Us
            </h3>
            <p className="text-gray-500 text-[15px] leading-relaxed">
              We crave good clean food, but we are also lazy like you all. And, that's why we made these instant marinades.
            </p>
          </div>

          {/* Help & About Section */}
          <div className="flex-shrink-0 min-w-[140px]">
            <h3 className="text-xs font-medium tracking-[0.15em] text-gray-800 uppercase mb-4">
              Help & About
            </h3>
            <ul className="flex flex-col gap-3">
              <li>
                <a href="/pages/our-policies" className="text-gray-500 hover:text-gray-900 text-[15px] transition-colors">
                  Our Policies
                </a>
              </li>
              <li>
                <a href="/pages/contact-us" className="text-gray-500 hover:text-gray-900 text-[15px] transition-colors">
                  Contact Us
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* Copyright Section */}
        <div className="mt-16">
          <p className="text-[10px] tracking-[0.1em] text-gray-500 uppercase">
            &copy; 2025 - KILRR
          </p>
        </div>
      </div>
    </footer>
  );
};

// ========== SHARED FOOTER ==========
const SharedFooter = () => {
  return (
    <section data-section="about-us" className="w-full bg-white py-20 px-6 md:px-12 lg:px-24">
      <div className="max-w-[1400px] mx-auto grid grid-cols-1 md:grid-cols-12 gap-y-12 md:gap-y-0">
        
        {/* Left Column: Logo & Copyright */}
        <div className="md:col-span-4 flex flex-col justify-between h-full min-h-[160px]">
          {/* Logo */}
          <div className="flex-shrink-0">
             <img 
               src="./assets/img-60.png" 
               alt="Kilrr Logo" 
               className="w-[140px] h-[50px] object-contain object-left" 
             />
          </div>
          
          {/* Copyright */}
          <div className="mt-auto pt-12 md:pt-0">
            <p className="text-[11px] uppercase tracking-[0.15em] text-gray-500 font-medium">
              © 2025 - KILRR
            </p>
          </div>
        </div>

        {/* Middle Column: About Us */}
        <div className="md:col-span-4 md:col-start-5">
          <h3 className="text-[13px] font-medium uppercase tracking-[0.15em] text-gray-900 mb-8">
            ABOUT US
          </h3>
          <p className="text-gray-500 text-[16px] leading-relaxed font-light max-w-sm">
            We crave good clean food, but we are also lazy like you all. And, that's why we made these instant marinades.
          </p>
        </div>

        {/* Right Column: Help & About */}
        <div className="md:col-span-3 md:col-start-10 md:pl-12">
          <h3 className="text-[13px] font-medium uppercase tracking-[0.15em] text-gray-900 mb-8">
            HELP & ABOUT
          </h3>
          <ul className="flex flex-col space-y-5">
            <li>
              <a href="/pages/our-policies" className="text-gray-500 hover:text-gray-900 text-[16px] font-light transition-colors">
                Our Policies
              </a>
            </li>
            <li>
              <a href="/pages/contact-us" className="text-gray-500 hover:text-gray-900 text-[16px] font-light transition-colors">
                Contact Us
              </a>
            </li>
          </ul>
        </div>

      </div>
    </section>
  );
};

// ========== MAIN APP ==========
const App = () => {
  return (
    <div className="min-h-screen">
      <Section2 />
      <SharedFooter />
    </div>
  );
};