// Generated by PixelGen v2 - Multi-Page with Shared Components
// Page: pages-contact-us

// ========== PAGES-CONTACT-US CONTENT 1 ==========
const Section2 = () => {
  return (
    <footer data-section="about-us" className="w-full bg-white pt-14 pb-8 px-6 md:px-12 lg:px-20">
      <div className="max-w-[1200px] mx-auto">
        <div className="flex flex-col md:flex-row justify-between items-start">
          
          {/* Logo Column */}
          <div className="mb-10 md:mb-0 md:w-1/4 flex-shrink-0">
            <img 
              src="./assets/img-1.png" 
              alt="Kilrr Logo" 
              className="w-[140px] h-auto object-contain"
            />
          </div>

          {/* About Us Column */}
          <div className="mb-10 md:mb-0 md:w-5/12 lg:w-1/3 md:pl-4">
            <h3 className="text-[11px] font-medium tracking-[0.15em] text-gray-800 uppercase mb-5">
              About Us
            </h3>
            <p className="text-[15px] leading-7 text-gray-500 font-normal">
              We crave good clean food, but we are also lazy like you all. And, that's why we made these instant marinades.
            </p>
          </div>

          {/* Help & About Column */}
          <div className="md:w-1/4 flex flex-col md:items-start md:pl-10 lg:pl-24">
            <h3 className="text-[11px] font-medium tracking-[0.15em] text-gray-800 uppercase mb-5">
              Help & About
            </h3>
            <div className="flex flex-col space-y-4">
              <span className="text-[15px] text-gray-500 cursor-pointer hover:text-gray-700 transition-colors">
                Our Policies
              </span>
              <span className="text-[15px] text-gray-500 cursor-pointer hover:text-gray-700 transition-colors">
                Contact Us
              </span>
            </div>
          </div>
        </div>

        {/* Copyright Section */}
        <div className="mt-20 md:mt-24">
          <p className="text-[10px] tracking-[0.1em] text-gray-500 uppercase font-medium">
            © 2025 - KILRR
          </p>
        </div>
      </div>
    </footer>
  );
};

// ========== SHARED FOOTER ==========
const SharedFooter = () => {
  return (
    <section data-section="about-us" className="w-full bg-white py-20 px-8 md:px-16 lg:px-24">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-12 md:gap-8">
        
        {/* Left Column: Logo & Copyright */}
        <div className="md:col-span-5 flex flex-col justify-between h-full min-h-[140px]">
          <div className="mb-8 md:mb-0">
            <img 
              src="./assets/img-60.png" 
              alt="Kilrr Logo" 
              className="w-[140px] h-auto object-contain" 
            />
          </div>
          <div className="mt-auto hidden md:block">
            <p className="text-[10px] tracking-[0.2em] text-gray-400 uppercase font-medium">
              © 2025 - KILRR
            </p>
          </div>
        </div>

        {/* Middle Column: About Us */}
        <div className="md:col-span-4">
          <h3 className="text-[11px] font-semibold tracking-[0.2em] text-gray-800 uppercase mb-8">
            About Us
          </h3>
          <p className="text-gray-500 text-[15px] leading-7 font-light max-w-md">
            We crave good clean food, but we are also lazy like you all. And, that's why we made these instant marinades.
          </p>
        </div>

        {/* Right Column: Help & About */}
        <div className="md:col-span-3 md:pl-12">
          <h3 className="text-[11px] font-semibold tracking-[0.2em] text-gray-800 uppercase mb-8">
            Help & About
          </h3>
          <ul className="flex flex-col space-y-3">
            <li>
              <a href="#" className="text-gray-500 text-[15px] font-light hover:text-gray-900 transition-colors">
                Our Policies
              </a>
            </li>
            <li>
              <a href="#" className="text-gray-500 text-[15px] font-light hover:text-gray-900 transition-colors">
                Contact Us
              </a>
            </li>
          </ul>
        </div>

        {/* Mobile Copyright */}
        <div className="md:hidden mt-4">
            <p className="text-[10px] tracking-[0.2em] text-gray-400 uppercase font-medium">
              © 2025 - KILRR
            </p>
        </div>

      </div>
    </section>
  );
};

// ========== MAIN APP ==========
const App = () => {
  return (
    <div className="min-h-screen">
      <Section2 />
      <SharedFooter />
    </div>
  );
};